### ISSUE TITLE
Gen 5 SVG styles

### ISSUE THREAD

**Issue by gerwitz** [TheArtificial/pokemon-icons#13]
@pabluxo91 - PR #12 worked well (I still have to manually deploy because I haven't gotten Travis working right) … but because the SVGs have CSS definitions instead of inline attributes, they don't render with color on the index page.

Can you adjust the new SVGs with inline fills?

**Comment by pabluxo91** [comment]
I'm sorry, I didn't know inline attributes were required. I changed the svg exporting options in Illustrator so It should be resolved. I also included other stuff in my last commit, please take a look on it. And I don't know about Travis but if I can help just let me know.

**Comment by gerwitz** [comment]
I see you closed #14 as well. Looks good!

I tried to set up Travis to auto-push into the gh-pages branch after building, but my Gulp skills aren't up to the challenge of making everything serial enough. ¯\\\_(ツ)\_/¯ because it's trivial for me to run it locally.

**Comment by pabluxo91** [comment]
haha well in that case, beeing trivial to run it locally, it doens't seem such a big problem. Glad to heard that!
