### ISSUE TITLE
Use svgo for optimizing SVG files

### ISSUE THREAD

**Issue by KovuTheHusky** [TheArtificial/pokemon-icons#18]
Using [svgo](https://github.com/svg/svgo) removes redundant or useless information from SVG files.

I ran `find _icons/SVG -type f -name "*.svg" -exec svgo --multipass {} \;` from the project root and found that the directory size went from 10.2MB to 7.4MB which is a decrease of ~27%.

Using svgo could be automated by being integrated into your gulp tasks. Would save a good deal of bandwidth when serving the files on the web.

**Comment by gerwitz** [comment]
Good idea … when the icon set was manually managed (a few generations ago) we used svgo but it didn't get scripted in when we automated things.

I'll get to it eventually, but pull requests are greatly appreciated. ;-)

**Comment by gerwitz** [comment]
Oh, and if you have gulp skills, I'd love thoughts on fixing the `publish` task. It's currently running subtasks asynchronousy and thus failing on Travis CI.

**Comment by gerwitz** [comment]
All done and deployed
