### ISSUE TITLE
I have all the gen 5 pokemons

### ISSUE THREAD

**Issue by lepunk** [TheArtificial/pokemon-icons#3]
Hi all,
I'm using this artwork in my app (PokeBuddy). When the announcement came out that Pokemon Go will add gen 5 to the roster I hired a freelancer to draw the pokemons in the same style as gen 1-4.

I would like to contribute the set to this repo. The problem however is that she did it in photoshop and I'm not a designer so can't really convert it to ai. 
Would you be interested?

**Comment by dandesousa** [comment]
Maybe you can make a pull request for them. I'd be interested in leveraging these from your branch even if they don't accept it

**Comment by gerwitz** [comment]
A pull request would be perfect! It sounds like you have only Photoshop files -- maybe try adding your source files to `_working`. Hopefully your designer used vectors and we can help turn them into compatible assets.

**Comment by lepunk** [comment]
Thanks @gerwitz PR submitted, it's bit messy but hope it helps
