### ISSUE TITLE
Generation 5 Timeline / Help Offer

### ISSUE THREAD

**Issue by dandesousa** [TheArtificial/pokemon-icons#4]
First I just want to say thank you for putting this up on GitHub. These icons are greatly enjoyed throughout the Pokemon Go discord community through the bot I develop (PokeNav).

I wanted to see if there was anything I could do to help with getting the Gen 5 icons ready (assuming they are planned). I noticed #3 mentioned the availability of an icon set, but I'm unsure what the workflow is like for getting them accepted. 

Appreciate all the time and effort you put into this.

**Comment by gerwitz** [comment]
Thanks! The README file covers the basics of adding assets, but we're working on more guidance. Mostly, be sure to use vectors: the SVGs are "canonical", but design to 32x32 pixels (it's very tempted to add too much detail!)

There are working files for Adobe Illustrator under `_working`, which for now is the best place to see what we've already made progress on.

**Comment by dandesousa** [comment]
Looks like theres a PR
